frigate:

  env:
    TZ: "America/Chicago"

  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.15
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - frigate.k3s.home  
    path: /
    