apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-system
spec:
  generators:
  - git:
      repoURL: https://github.com/craigness24/craigshome-k8s.git
      revision: master
      directories:
      - path: kube-system/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default
      source:
        repoURL: https://github.com/craigness24/craigshome-k8s.git
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true