apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
spec:
  generators:
  - git:
      repoURL: https://github.com/craigness24/craigshome-k8s.git
      revision: main
      directories:
      - path: platform/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: homelab
      source:
        repoURL: https://github.com/craigness24/craigshome-k8s.git
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true