frigate:

  image:
    repository: blakeblackshear/frigate
    tag: 0.9.1-amd64
  coral:
    enabled: true
  env:
    TZ: "America/New_York"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - frigate.k3s.home
  
  shmSize: 2Gi

  persistence:
    data:
      enabled: true
      # size: 10Gi
      # ## Do not delete the pvc upon helm uninstall
      # skipuninstall: true
      # existingClaim: frigate
  extraVolumes:
    - name: cache
      emptyDir:
        medium: Memory
  extraVolumeMounts:
    - mountPath: /tmp/cache
      name: cache

  probes:
    startup:
      enabled: true

  # frigate configuration - see https://github.com/blakeblackshear/frigate/blob/master/config/config.yml for example
  config: |
    # Optional: detectors configuration
    # USB Coral devices will be auto detected with CPU fallback
    detectors:
      # Required: name of the detector
      coral:
        # Required: type of the detector
        # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
        type: edgetpu
        # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
        device: usb

    mqtt:
      host: mosquitto.platform.svc.cluster.local
      port: 1883
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      client_id: frigate

    # Optional: birdseye configuration
    birdseye:
      # Optional: Enable birdseye view (default: shown below)
      enabled: True
      # Optional: Width of the output resolution (default: shown below)
      width: 1920
      # Optional: Height of the output resolution (default: shown below)
      height: 1080
      # Optional: Encoding quality of the mpeg1 feed (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8
      # Optional: Mode of the view. Available options are: objects, motion, and continuous
      #   objects - cameras are included if they have had a tracked object within the last 30 seconds
      #   motion - cameras are included if motion was detected in the last 30 seconds
      #   continuous - all cameras are included always
      mode: objects

    # Optional: Global ffmpeg args
    # "ffmpeg" + global_args + input_args + "-i" + input + output_args
    ffmpeg:
      # Optional: global ffmpeg args (default: shown below)
      global_args:
        - -hide_banner
        - -loglevel
        - warning
      # Optional: global hwaccel args (default: shown below)
      # NOTE: See hardware acceleration docs for your specific device
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      # Optional: global input args (default: shown below)
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'

    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10

    # NOTE: Can be overridden at the camera level
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 240
      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 8

    detect:
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 352
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 240
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    # Optional: Global object filters for all cameras.
    # NOTE: can be overridden at the camera level
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      # Optional: filters to reduce false positives for specific object types
      # filters:
        # person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          # min_area: 5000
          # # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
          # max_area: 100000
          # # Optional: minimum score for the object to initiate tracking (default: shown below)
          # min_score: 0.5
          # # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          # threshold: 0.85

    # Required: configuration section for cameras
    cameras:
      # Required: name of the camera
      BFence:
        # Required: ffmpeg settings for the camera
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch01/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch01/0
              roles:
                - rtmp
        # motion:
        #   mask:
        #     - 630,297,0,423,0,257,0,0,1600,0,1920,0,1920,243
        best_image_timeout: 60
      Utils:
        ffmpeg:
          inputs: 
            - path: rtsp://192.168.1.107/ch02/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch02/0
              roles:
                - rtmp
        best_image_timeout: 60
      BYard:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch03/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch03/0
              roles:
                - rtmp
        best_image_timeout: 60
        mqtt:
          crop: True
          height: 300
      Driveway:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch04/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch04/0
              roles:
                - rtmp
        # motion:
        #   mask:
        #     - 1023,0,1920,0,1920,548,1177,408,649,323,537,302,122,292,0,248,0,0
        best_image_timeout: 60
      BPorch:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch05/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch05/0
              roles:
                - rtmp
        best_image_timeout: 60
      Garage:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch06/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch06/0
              roles:
                - rtmp
        best_image_timeout: 60
      Brzeway:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch07/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch07/0
              roles:
                - rtmp
                - record
        best_image_timeout: 60
      FYard:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.107/ch08/1
              roles:
                - detect
            - path: rtsp://192.168.1.107/ch08/0
              roles:
                - rtmp
        best_image_timeout: 60
