home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 2021.10.0
    pullPolicy: IfNotPresent
  env:
    TZ: "America/Chicago"
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    main:
      type: LoadBalancer
      ports:
        http:
          port: 80

      #loadBalancerIP: 192.168.1.11
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: hass.k3s.home
        paths:
        - path: /
          pathType: Prefix
          