home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 2021.10.0
  env:
    TZ: "America/Chicago"
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.152