home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 2021.10.0
    pullPolicy: IfNotPresent
  env:
    TZ: "America/Chicago"
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  # service:
    # main:
  #     type: LoadBalancer
      # ports:
        # http:
          # port: 80
          # targetPort: 8123

      #loadBalancerIP: 192.168.1.11
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.org/websocket-services: home-assistant
      hosts:
      - host: hass.k3s.home
        paths:
        - path: /
          pathType: Prefix

          # service:
          #   name: home-assistant
          #   port: 80
  probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
  persistence:
    config:
      enabled: true
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: "10Gi"
  podAnnotations:
    backup.velero.io/backup-volumes: config
  addons:
    codeserver:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.12.0
      workingDir: "/config"
      args:
        - --user-data-dir
        - "/config/.vscode"
        - --auth
        - "none"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
        hosts:
        - host: hass-vscode.eviljungle.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - hass-vscode.eviljungle.com
      volumeMounts:
      - name: config
        mountPath: /config
  tolerations:
  - key: "arm"
    operator: "Exists"
  resources:
    limits:
      memory: 2500Mi
    requests:
      cpu: 100m
      memory: 1000Mi
  postgresql:
    enabled: true
    postgresqlUsername: home-assistant
    postgresqlDatabase: home-assistant
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"

