ingress-nginx:
  controller:
    hostPort:
      enabled: true
    kind: DaemonSet
    metrics:
      enabled: true
    # publishService:
    #   enabled: false
    # extraArgs:
    #   default-ssl-certificate: "nginx/default-ssl-certificate"
    service:
      loadBalancerIP: 192.168.1.24
      externalTrafficPolicy: Local
    ingressClassResource:
        default: true
    resources:
      limits:
        cpu: 100m
        memory: 90Mi
      requests:
        cpu: 100m
        memory: 90Mi