hostname: k3s-s1
ssh_authorized_keys:
  - github:craigness24
write_files:
  - path: /var/lib/connman/default.config
    content: |-
      [service_eth0]
      Type=ethernet
      IPv4=192.168.1.124/255.255.255.0/192.168.1.1
      IPv6=off
      Nameservers=192.168.1.1

k3os:
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
  dns_nameservers:
    - 192.168.1.1
    - 9.9.9.9
    - 1.1.1.1
  k3s_args:
    - server
    - "--no-deploy"
    - "traefik"
